In [1]:
import numpy as np

In [2]:
a=np.array([0,1,2,3,4,5])

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a.ndim

1

In [5]:
a.shape

(6,)

In [6]:
b=a.reshape((3,2))
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
b.ndim

2

In [8]:
b.shape

(3, 2)

In [9]:
b[1][0]=7
b
a

array([0, 1, 7, 3, 4, 5])

In [10]:
b

array([[0, 1],
       [7, 3],
       [4, 5]])

In [11]:
c=a.reshape((3,2)).copy()

In [12]:
c

array([[0, 1],
       [7, 3],
       [4, 5]])

In [13]:
c[0][0]=-99

In [14]:
a
c

array([[-99,   1],
       [  7,   3],
       [  4,   5]])

In [15]:
a

array([0, 1, 7, 3, 4, 5])

In [16]:
#Operatives are propogated to indiidual elements

In [17]:
a*2

array([ 0,  2, 14,  6,  8, 10])

In [18]:
a**2

array([ 0,  1, 49,  9, 16, 25], dtype=int32)

In [19]:
#This doesx not happen with ordinary python lists

In [20]:
a[np.array([2,3,4])]

array([7, 3, 4])

In [21]:
a[a>4]

array([7, 5])

In [22]:
a[a>4]=4
a

array([0, 1, 4, 3, 4, 4])

In [23]:
#As this is a frequent use case, there is a special clip function for it, clipping the values at both ends of an interval with one function call as follows:
a.clip(0,4)

array([0, 1, 4, 3, 4, 4])

In [24]:
#NON-EXISTING VALUES HANDLING
c = np.array([1,2,np.NAN,3,4])

In [25]:
c

array([ 1.,  2., nan,  3.,  4.])

In [26]:
np.isnan(c)

array([False, False,  True, False, False])

In [27]:
c[~np.isnan(c)]

array([1., 2., 3., 4.])

In [28]:
np.mean(c[~np.isnan(c)])

2.5

In [29]:
#However, the speed comes at a price. Using NumPy arrays, we no longer have the 
#incredible flexibility of Python lists, which can hold basically anything. NumPy 
#arrays always have only one datatype.
#If we try to use elements of different types, NumPy will do its best to coerce them 
#to the most reasonable common datatype